baseURL = "https://he-arc.github.io/2243.2-Genie_Logiciel/"
relativeURLs = false
languageCode = "fr"
title = "HE-Arc 2243.2 Génie Logiciel"
theme = "book"
enableGitInfo = true

[params]
BookSearch = false

[Taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe= true
